"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestIngSoftModel,
	#superclass : #PackageManifest,
	#category : #'IngSoft2-Model'
}

{ #category : #'code-critics' }
ManifestIngSoftModel class >> ruleRBExcessiveVariablesRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'IngSoft2-Model')) #'2019-02-25T22:02:19.502452-03:00') )
]
